apiVersion: apps/v1
kind: Deployment
metadata:
 name: chatbot
 labels:
   app: chatbot
spec:
 replicas: 1
 selector:
   matchLabels:
     app: chatbot
 template:
   metadata:
     labels:
       app: chatbot
   spec:
     containers:
     - name: chatbot
       image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/chatbot:rag-v3a
       command: ["python"]
       args: ["chatbot.py"]
       imagePullPolicy: IfNotPresent
       resources:
         limits:
           nvidia.com/gpu: 1
       ports:
       - containerPort: 7860
       volumeMounts:
         - mountPath: /dev/shm
           name: dshm
     volumes:
     - emptyDir:
         sizeLimit: 1Gi
         medium: Memory
       name: dshm

